spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: voting
      authentication-database: admin

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false